version: '3.1'

services:
  db:
    container_name: eva_mongo
    image: mongo
    restart: always
    ports:
      - "3306:3306"
  mq:
    container_name: eva_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
